apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-python
  labels:
    app: {{ .Release.Name }}-python
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-python
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-python
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash"]
          args: ["-c", "sleep 3600"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
