# Default values for python-app
replicaCount: 1

image:
  repository: python
  tag: "3.12-slim"  # Latest stable Python version
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
